backend:
  name: github
  repo: EkramulKU/kuws-website
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "notices"
    label: "Notices"
    folder: "content/notices"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "body", widget: "markdown" }

  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Event Title", name: "title", widget: "string" }
      - { label: "Event Date", name: "date", widget: "datetime" }
      - { label: "Details", name: "body", widget: "markdown" }

  - name: "honorboard"
    label: "Honor Board"
    folder: "content/honorboard"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Achievement", name: "body", widget: "markdown" }
      - { label: "Year", name: "year", widget: "string" }
