backend:
  name: github
  repo: EkramulKU/kuws-website
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "notices"
    label: "Notices"
    folder: "content/notices"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }

      - { label: "Publish Date", name: "date", widget: "datetime" }

      - { label: "Show on Home Page (Marquee)", name: "show_on_home", widget: "boolean", default: false }

      - { label: "Pinned (Show First)", name: "pinned", widget: "boolean", default: false }

      - { label: "Urgent Notice", name: "urgent", widget: "boolean", default: false }

      - { label: "Expire After (optional)", name: "expiry", widget: "datetime", required: false }

      - { label: "Description", name: "body", widget: "markdown" }

  - name: "events"
    label: "Events"
    folder: "content/events"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Event Title", name: "title", widget: "string" }
      - { label: "Event Date", name: "date", widget: "datetime" }
      - { label: "Details", name: "body", widget: "markdown" }

  - name: "honorboard"
    label: "Honor Board"
    folder: "content/honorboard"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Name", name: "title", widget: "string" }
      - { label: "Achievement", name: "body", widget: "markdown" }
      - { label: "Year", name: "year", widget: "string" }
